_target_: sac_diffusion.datasets.calvin_critic_offline_dataset.CalvinCriticOfflineDataset
skill: ${skill} # 这里面有 state_type 配置
goal_centered: True
flatten: False
demos_dir: ${demos_dir}
#state_type: "pos_ori_grip"
data_type: "training"

is_quaternion: False
use_visual_obs: True
mode: "gaussian"
