# Environment params
env_name: calvin
show_gui: ${show_gui}
ee_noise: [0.03, 0.03, 0.03]
obs_space: ["pos","joints","state","gripper"] # ["state"], ["pos", "joints"], ["pos", "joints", "gripper"], ["state", "gripper"]
